export const homeLinks = [
    {
        href: "eventos",
        titulo: "Atrações",
        dias: "todos",
        color: "#8E3200",
        id: 1,
    },
    {
        href: "entradas",
        titulo: "Entradas",
        dias: "todos",
        color: "#f5f5dc",
        id: 2,
    },
    {
        href: "sexta",
        titulo: "Pratos Principais",
        dias: "sexta",
        color: "#f5f5dc",
        id: 3,
    },
    {
        href: "moquecas",
        titulo: "Moquecas",
        dias: "sab-dom",
        color: "#f5f5dc",
        id: 4,
    },
    {
        href: "peixes-frutos-mar",
        titulo: "Peixes e Frutos do Mar",
        dias: "sab-dom",
        color: "#f5f5dc",
        id: 5,
    },
    {
        href: "carnes-aves-risotos",
        titulo: "Carnes, Aves e Risotos",
        dias: "sab-dom",
        color: "#f5f5dc",
        id: 6,
    },
    {
        href: "bebidas",
        titulo: "Bebidas",
        dias: "todos",
        color: "#f5f5dc",
        id: 7,
    },
    {
        href: "vinhos",
        titulo: "Carta de Vinhos",
        dias: "todos",
        color: "#f5f5dc",
        id: 8,
    },
    {
        href: "sobremesas",
        titulo: "Sobremesas",
        dias: "todos",
        color: "#f5f5dc",
        id: 9,
    },
    // {
    //     href: "promo",
    //     titulo: "Promoções",
    //     dias: "todos",
    //     color: "#8E3200",
    // },
];
