import React, { useState } from "react";
import Head from "next/head";
import Principal from "./components/Principal";

export default function Home() {
    const timeElapsed = Date.now();
    const today = new Date(timeElapsed);
    const diaHoje = today.toDateString();
    

    return (
        <>
            <Head>
                <title>Cozinha Massari Menu</title>
                <meta
                    name="description"  
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Principal></Principal>
        </>
    );
}
