import React, { useState } from "react";
import Head from "next/head";
import Principal from "./components/Principal";


export default function Home() {
    return (
        <>
            <Head>
                <title>Cozinha Massari Menu</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="shortcut icon" href="/favicon.ico" />
            </Head>
            <Principal></Principal>
        </>
    );
}
